url: https://openexchangerates.org/api/
param:
  appId: 700744bf017345169e132f0e2a83e98a
  base: USD
  alternative: RUB
  opponent: EUR
  daysAgo: 1000
urlImg: https://api.giphy.com/v1/gifs
paramImg:
  apiKey: fPziAd9dTCFm2dEu3t2OVvThNl5SG1tw